version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    depends_on: 
      - db
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure