version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: assortedbits.azurecr.io/django-tenants
    depends_on: 
      - db
    environment:
      - PUBLIC_TENANT_DOMAIN=${PUBLIC_TENANT_DOMAIN}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    ports:
      - 8000:8000
    restart: on-failure