version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: assortedbits.azurecr.io/django-tenants
    depends_on: 
      - db
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PUBLIC_TENANT_DOMAIN=${PUBLIC_TENANT_DOMAIN}
    ports:
      - 8000:8000
    restart: on-failure