version: "3.3"
   
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on: 
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.local
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
  web:
    ports:
      - 80:8000
    volumes:
      - .:/code