version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: assortedbits.azurecr.io/django-tenants
    depends_on: 
      - db
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=foobar@local
      - ADMIN_PASSWORD=password
    ports:
      - 8000:8000
    volumes:
      - .:/code